service: lambda-dynamodb-crud-sqs

provider:
  name: aws
  runtime: java17
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource:
            - "arn:aws:dynamodb:us-east-2:418295712215:table/usuarios"
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - "arn:aws:sqs:us-east-2:418295712215:UserCreationQueue"
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
          Resource:
            - "arn:aws:sqs:us-east-2:418295712215:UserCreationQueue"
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - "arn:aws:sns:us-east-2:418295712215:UserNotifications"

package:
  artifact: target/api-serverles-users-1.0-SNAPSHOT.jar

resources:
  Resources:
    UserCreationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UserCreationQueue

    UserNotifications:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: UserNotifications

functions:
  createUser:
    handler: org.example.CreateUserHandler
    events:
      - http:
          path: usuarios
          method: post
    environment:
      USER_CREATION_QUEUE_URL:
        Ref: UserCreationQueue

  sendEmail:
    handler: org.example.SendEmailHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UserCreationQueue
              - Arn
    environment:
      SNS_TOPIC_ARN:
        Ref: UserNotifications
